import test from 'node:test';
import assert from 'node:assert/strict';
import { kernel, document } from './helpers.js';
import { HarnessKnowledge, type HarnessState } from '../packages/integrations/dsh/knowledge.js';
import { registerKnowledgeTools, type DshTool } from '../packages/integrations/dsh/plugin.js';
const make = () => new HarnessKnowledge(kernel(document('a', '# Promise\nMicrotask\n\n## Order\nMicrotask\nEvent Loop\n'), document('b', '# Microtask\nPromise\n'), document('c', '# Event Loop\nScheduling\n')));
const action = (k: HarnessKnowledge, command: unknown, sessionId = 'human') => k.human({ type: 'workspace', sessionId, command }) as HarnessState;
test('DSH Follow Lens isolates human sessions, rejects outside evidence and stale versions; only human approval expands scope', () => {
  const k = make(); action(k, { type: 'focus', id: 'a' }); action(k, { type: 'lens', value: 0 });
  assert.equal(k.promptContext('human'), ''); assert.throws(() => k.context('human'), /Enable Follow/);
  k.human({ type: 'follow', sessionId: 'human', enabled: true });
  const original = k.context('human'); assert.equal(original.relations.length, 1); assert.match(original.center.text, /Promise/);
  assert.throws(() => k.document('human', original.version, 'c'), /outside/);
  assert.equal(k.document('human', original.version, 'a', 0, 5).nextOffset, 5);
  const pending = k.propose('human', original.version, '检查任务调度与微任务的关系', 2);
  assert.equal(pending.proposals.length, 1); assert.equal(k.context('human').relations.length, 1);
  assert.equal(JSON.stringify(pending).includes('Scheduling'), false);
  const outside = k.service.getRelations('a').find(r => r.nodes.includes('c'))!.signals[0]!.evidence[0]!;
  assert.throws(() => k.evidence('human', original.version, outside), /outside/);
  k.human({ type: 'decision', sessionId: 'human', proposalId: pending.proposals[0]!.id, approve: true });
  const expanded = k.context('human'); assert.ok(expanded.relations.length > 0);
  assert.throws(() => k.evidence('human', original.version, outside), /scope changed/);
  const locator = expanded.relations[0]!.signals[0]!.evidence[0]!;
  assert.equal(k.evidence('human', expanded.version, locator).status, 'valid');
  assert.equal(k.state('other').harness.followLens, false); assert.equal(k.promptContext('other'), '');
  const prior = k.state('human').current; action(k, { type: 'focus', id: 'b' }); action(k, { type: 'back' }); assert.deepEqual(k.state('human').current, prior);
  const stale = k.context('human'); action(k, { type: 'lens', value: 0 }); assert.throws(() => k.propose('human', stale.version, 'test'), /scope changed/);
  assert.throws(() => action(k, { type: 'save', id: 'a', expectedHash: '', markdown: 'overwrite' }), /read-only/);
  k.close(); assert.throws(() => k.state('human'), /closed/);
});
test('DSH native registration never exposes human commands and disposes tools and prompt providers', async () => {
  const k = make(); const tools = new Map<string, DshTool>(); const providers = new Map<string, unknown>();
  const register = (x: { name: string }) => { providers.set(x.name, x); return () => { providers.delete(x.name); }; };
  const dispose = registerKnowledgeTools({ tools: { register(tool) { tools.set(tool.name, tool); return () => { tools.delete(tool.name); }; } }, systemPrompt: { context: register, section: register, variable(name, provider) { return register({ name, provider } as { name: string }); } } }, k);
  assert.deepEqual([...tools.keys()], ['ripple_context', 'ripple_document', 'ripple_evidence', 'ripple_propose_beyond']);
  await assert.rejects(tools.get('ripple_context')!.execute({}, { signal: new AbortController().signal }), /agent session/);
  k.human({ type: 'follow', sessionId: 'human', enabled: true });
  const result = JSON.parse(await tools.get('ripple_context')!.execute({}, { agent: { id: 'human' }, signal: new AbortController().signal }));
  assert.equal(result.version, k.context('human').version);
  const prompt = providers.get('ripple_knowledge_context') as { provider(x: { scope: { id: string } }): string };
  assert.equal(JSON.parse(prompt.provider({ scope: { id: 'human' } })).rippleKnowledge.version, result.version);
  dispose(); dispose(); assert.equal(tools.size, 0); assert.equal(providers.size, 0);
});
